#!/bin/bash

set -eux

checkfile=backup-pgees-voyager

targetbase=/media/85f3f57e-32fd-4c0e-a452-3c437fe2c775



bindmountdir=/root/tmp/"$checkfile"

checkfilepath="$targetbase/$checkfile"

if ! [ -f "$checkfilepath" ]; then
    echo "Vermisse Datei '$checkfilepath' als Sicherheitspruefung. Stoppe."
    exit 1
else
    mkdir -m 0700 -p "$bindmountdir"
    mount --bind / "$bindmountdir"
    rsync -aH --delete --exclude=/home/ --exclude=/lost+found/ "$bindmountdir" "$targetbase"
    mkdir -p "$targetbase"/home/
    umount "$bindmountdir"
    mount --bind /home/ "$bindmountdir"
    rsync -aH --delete --exclude=/lost+found/ "$bindmountdir" "$targetbase"/home
fi

